<?php

namespace AppBundle\Repository;

/**
 * ComidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComidaRepository extends \Doctrine\ORM\EntityRepository
{
}
