<?php

namespace AppBundle\Repository;

/**
 * PlatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatosRepository extends \Doctrine\ORM\EntityRepository
{
}
